# Generated by Django 4.1.6 on 2023-02-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acheivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الإنجاز')),
                ('date', models.DateField(verbose_name='تاريخ الإنجاز')),
                ('text', models.CharField(max_length=1000, verbose_name='نص الإنجاز')),
            ],
        ),
        migrations.CreateModel(
            name='Cretificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(max_length=150, verbose_name='الجهة المقدم منها الشهادة')),
                ('date', models.DateField(verbose_name='تاريخ الشهادة')),
                ('text', models.CharField(max_length=1000, verbose_name='نص الشهادة')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الخطة العلاجية')),
                ('date', models.DateField(verbose_name='تاريخ الخطة العلاجية')),
                ('text', models.CharField(blank=True, max_length=1000, verbose_name='تفاصيل عن الخطة العلاجية')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الزيارة')),
                ('date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('text', models.CharField(blank=True, max_length=1000, verbose_name='تفاصيل عن الزيارة')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الورشة')),
                ('text', models.CharField(blank=True, max_length=1000, verbose_name='تفاصيل عن الورشة')),
            ],
        ),
    ]
