# Generated by Django 4.1.6 on 2023-02-09 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cretificate',
            old_name='auth',
            new_name='name',
        ),
    ]
